site_name: MkDocs Template
site_url: https://matthew-shaw.github.io/mkdocs
copyright: Copyright &copy; 2024 Matthew Shaw
repo_url: https://github.com/matthew-shaw/mkdocs
edit_uri: edit/main/docs/
watch:
  - includes

nav:
  - index.md
  - tags.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - git-committers:
      repository: matthew-shaw/mkdocs
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/matthew-shaw
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/matthew-shaw
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.me.uk/@mash
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/MattShaw85